#!/bin/sh
# lib/origin-trust.sh — origin (Harness) trust decision for gh-issue:implement
# (Step 3.1b) and gh-issue:proceed (Step 2.1.1b). Issue #44.
#
# SSOT for "who wrote this issue, and do we trust them enough to start without
# a plausibility review". EXECUTE it, feeding the issue body on stdin — stdout
# is the whole product, mirroring lib/validate-protocol.sh's contract:
#
#   ORIGIN=$(printf '%s' "$BODY" | bash "$PLUGIN_ROOT/lib/origin-trust.sh") \
#       || ORIGIN="ORIGIN_TRUST=review ORIGIN_HARNESS=unknown"
#
# The `||` fallback is the fail-closed half (NF-1): a missing, unreadable or
# broken helper must degrade to `review`, never to `trusted`. Never `source`
# it — same convention as lib/claim-issue.sh and lib/validate-protocol.sh.
#
# Output is exactly one line:
#   ORIGIN_TRUST=<trusted|review|skipped> ORIGIN_HARNESS=<x> ORIGIN_MODEL=<y>
#
# Input format is owned by issue #43: a standalone line at the very bottom of
# the issue body reading `Generated by Harness(<harness>) and LLM(<model>)`.
# The LAST match wins (a quoted body may carry an older line above). Values
# are lower-cased and whitespace-normalised; an absent or unparseable line
# yields `unknown`, which is never trusted.
#
# Zero API calls — the body is already in the caller's hand.
#
# Self-check: lib/origin-trust.selfcheck.sh

set -u

# GH_ISSUE_SKIP_ORIGIN_GATE is the family's single escape hatch (D-5): no CLI
# flag. Exactly "1" and nothing else — lib/claim-issue.sh's GH_ISSUE_SKIP_*
# vars take any non-empty value, but this one gates a trust decision, so a
# typo'd `=0` or `=false` must keep the gate on. Same strict form as
# lib/ai-metrics-footer.sh's GH_DISABLE_AI_METRICS.
if [ "${GH_ISSUE_SKIP_ORIGIN_GATE:-}" = "1" ]; then
    printf 'ORIGIN_TRUST=skipped ORIGIN_HARNESS=unknown ORIGIN_MODEL=unknown\n'
    exit 0
fi

_norm() { # lower-case, trim, collapse inner whitespace to "-"
    printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]' \
        | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//; s/[[:space:]]+/-/g'
}

# tr -d '\r': GitHub serves issue bodies with CRLF line endings, which would
# otherwise leave a stray \r inside the LLM(...) capture and defeat matching.
# Surrounding whitespace is tolerated: a backfill tool or an editor leaving a
# trailing space should not silently push every issue onto the review path.
LINE=$(tr -d '\r' \
    | grep -E '^[[:space:]]*Generated by Harness\(.*\) and LLM\(.*\)[[:space:]]*$' \
    | tail -n 1)

HARNESS=unknown
MODEL=unknown
if [ -n "$LINE" ]; then
    # The `.*` are greedy on purpose: they backtrack to the LAST `) and LLM(`,
    # so a value containing its own parentheses is captured whole instead of
    # being truncated at the first inner `)` (agy review, PR #46).
    _h=$(_norm "$(printf '%s' "$LINE" | sed -E 's/^[[:space:]]*Generated by Harness\((.*)\) and LLM\(.*\)[[:space:]]*$/\1/')")
    _m=$(_norm "$(printf '%s' "$LINE" | sed -E 's/^[[:space:]]*Generated by Harness\(.*\) and LLM\((.*)\)[[:space:]]*$/\1/')")
    [ -z "$_h" ] || HARNESS=$_h
    [ -z "$_m" ] || MODEL=$_m
fi

# `-` not `:-`: an explicitly empty GH_TRUSTED_HARNESSES means "trust nobody",
# an unset one means the default set. Family-wide name, shared with
# dEitY719/gh-flow-skills#36 (D-3).
#
# `set -f` before the deliberately unquoted expansion below: word splitting is
# wanted, globbing is not. Without it `GH_TRUSTED_HARNESSES='*'` expands to the
# cwd's filenames, so a repo that happens to hold a file named `claude` silently
# promotes that harness to trusted (agy review, PR #46).
TRUST=review
set -f
if [ "$HARNESS" != unknown ]; then
    for _t in ${GH_TRUSTED_HARNESSES-claude codex}; do
        if [ "$(_norm "$_t")" = "$HARNESS" ]; then
            TRUST=trusted
            break
        fi
    done
fi
# Defensive restore (agy review, PR #46): nothing below globs today, but a
# statement added under here must not silently inherit `-f`.
set +f

printf 'ORIGIN_TRUST=%s ORIGIN_HARNESS=%s ORIGIN_MODEL=%s\n' "$TRUST" "$HARNESS" "$MODEL"
