#!/usr/bin/env bash
# Self-check for lib/origin-trust.sh (issue #44 F-6). No framework, no
# fixtures dir — every body is built inline:
#
#   bash lib/origin-trust.selfcheck.sh
#
# Exits non-zero on the first regression.
set -u

ROOT=$(cd -- "$(dirname -- "$0")/.." && pwd)
TARGET="$ROOT/lib/origin-trust.sh"
FAIL=0

chk() { # chk <label> <got> <want>
    if [ "$2" = "$3" ]; then
        echo "ok    $1"
    else
        echo "FAIL  $1: got '$2' want '$3'"
        FAIL=1
    fi
}

run() { # run <body>  -> the helper's single output line
    printf '%s' "$1" | bash "$TARGET"
}

BODY_HEAD='## TL;DR

Do the thing.
'

# 1. Trusted harness — both defaults.
chk "Harness(claude) is trusted" \
    "$(run "${BODY_HEAD}
Generated by Harness(claude) and LLM(opus-5)")" \
    "ORIGIN_TRUST=trusted ORIGIN_HARNESS=claude ORIGIN_MODEL=opus-5"
chk "Harness(codex) is trusted" \
    "$(run "${BODY_HEAD}
Generated by Harness(codex) and LLM(gpt-5)")" \
    "ORIGIN_TRUST=trusted ORIGIN_HARNESS=codex ORIGIN_MODEL=gpt-5"

# 2. Case is normalised before the allow-list compare.
chk "Harness(Claude) normalises to trusted" \
    "$(run "${BODY_HEAD}
Generated by Harness(Claude) and LLM(Opus-5)")" \
    "ORIGIN_TRUST=trusted ORIGIN_HARNESS=claude ORIGIN_MODEL=opus-5"

# 3. Untrusted harness — a real name that is simply not on the allow-list.
chk "Harness(opencode) falls to review" \
    "$(run "${BODY_HEAD}
Generated by Harness(opencode) and LLM(sonnet-4)")" \
    "ORIGIN_TRUST=review ORIGIN_HARNESS=opencode ORIGIN_MODEL=sonnet-4"

# 4. Unknown — the line is there but the harness field is empty.
chk "Harness() yields unknown + review" \
    "$(run "${BODY_HEAD}
Generated by Harness() and LLM()")" \
    "ORIGIN_TRUST=review ORIGIN_HARNESS=unknown ORIGIN_MODEL=unknown"

# 5. No origin line at all (every issue predating #43) — fail-closed.
chk "no origin line yields review" \
    "$(run "$BODY_HEAD")" \
    "ORIGIN_TRUST=review ORIGIN_HARNESS=unknown ORIGIN_MODEL=unknown"

# 6. Empty body — fail-closed (NF-1).
chk "empty body yields review" \
    "$(run "")" \
    "ORIGIN_TRUST=review ORIGIN_HARNESS=unknown ORIGIN_MODEL=unknown"

# 7. Broken format (trailing text after the close paren) does not match.
chk "malformed origin line yields review" \
    "$(run "${BODY_HEAD}
Generated by Harness(claude) and LLM(opus-5) — backfilled")" \
    "ORIGIN_TRUST=review ORIGIN_HARNESS=unknown ORIGIN_MODEL=unknown"

# 8. Multiple matches — the LAST one wins (a quoted body carries an older
#    line above the one this issue was actually written with).
chk "multiple origin lines: last match wins" \
    "$(run "${BODY_HEAD}
Generated by Harness(claude) and LLM(opus-5)

Quoted from elsewhere.

Generated by Harness(opencode) and LLM(sonnet-4)")" \
    "ORIGIN_TRUST=review ORIGIN_HARNESS=opencode ORIGIN_MODEL=sonnet-4"
chk "multiple origin lines: last match can be the trusted one" \
    "$(run "${BODY_HEAD}
Generated by Harness(opencode) and LLM(sonnet-4)

Generated by Harness(claude) and LLM(opus-5)")" \
    "ORIGIN_TRUST=trusted ORIGIN_HARNESS=claude ORIGIN_MODEL=opus-5"

# 8b. Nested parentheses inside either value. The greedy `.*` backtracks to the
#     LAST `) and LLM(`, so the value is captured whole rather than truncated at
#     the first inner `)` (agy review, PR #46 — reported as corruption; is not).
chk "parenthesised values are captured whole" \
    "$(run "${BODY_HEAD}
Generated by Harness(claude (code)) and LLM(opus-5 (1m))")" \
    "ORIGIN_TRUST=review ORIGIN_HARNESS=claude-(code) ORIGIN_MODEL=opus-5-(1m)"

# 8c. Leading/trailing whitespace on the line still matches.
chk "surrounding whitespace still matches" \
    "$(run "$(printf '## TL;DR\n\n   Generated by Harness(claude) and LLM(opus-5)   \n')")" \
    "ORIGIN_TRUST=trusted ORIGIN_HARNESS=claude ORIGIN_MODEL=opus-5"

# 8d. A glob-shaped override must not expand against the cwd. Run from a
#     directory holding files named after the default harnesses: without
#     `set -f` in the helper, `*` becomes `claude codex` and trusts them.
_globdir=$(mktemp -d) || exit 1
trap 'rm -rf "$_globdir"' EXIT
: >"$_globdir/claude"
: >"$_globdir/codex"
chk "GH_TRUSTED_HARNESSES='*' does not glob the cwd" \
    "$(cd "$_globdir" && printf '%s' "${BODY_HEAD}
Generated by Harness(claude) and LLM(opus-5)" | GH_TRUSTED_HARNESSES='*' bash "$TARGET")" \
    "ORIGIN_TRUST=review ORIGIN_HARNESS=claude ORIGIN_MODEL=opus-5"

# 9. CRLF bodies (what the GitHub API actually serves) still match.
chk "CRLF body still matches" \
    "$(run "$(printf '## TL;DR\r\n\r\nGenerated by Harness(claude) and LLM(opus-5)\r\n')")" \
    "ORIGIN_TRUST=trusted ORIGIN_HARNESS=claude ORIGIN_MODEL=opus-5"

# 10. GH_TRUSTED_HARNESSES narrows the set.
chk "GH_TRUSTED_HARNESSES='claude' demotes codex" \
    "$(printf '%s' "${BODY_HEAD}
Generated by Harness(codex) and LLM(gpt-5)" \
        | GH_TRUSTED_HARNESSES="claude" bash "$TARGET")" \
    "ORIGIN_TRUST=review ORIGIN_HARNESS=codex ORIGIN_MODEL=gpt-5"

# 11. GH_TRUSTED_HARNESSES widens the set.
chk "GH_TRUSTED_HARNESSES adds a harness" \
    "$(printf '%s' "${BODY_HEAD}
Generated by Harness(opencode) and LLM(sonnet-4)" \
        | GH_TRUSTED_HARNESSES="claude codex opencode" bash "$TARGET")" \
    "ORIGIN_TRUST=trusted ORIGIN_HARNESS=opencode ORIGIN_MODEL=sonnet-4"

# 12. An explicitly EMPTY override means "trust nobody" — not "use defaults".
chk "empty GH_TRUSTED_HARNESSES trusts nobody" \
    "$(printf '%s' "${BODY_HEAD}
Generated by Harness(claude) and LLM(opus-5)" \
        | GH_TRUSTED_HARNESSES="" bash "$TARGET")" \
    "ORIGIN_TRUST=review ORIGIN_HARNESS=claude ORIGIN_MODEL=opus-5"

# 13. A foot-gun override can never promote `unknown` to trusted (NF-1).
chk "GH_TRUSTED_HARNESSES='unknown' cannot trust a missing line" \
    "$(printf '%s' "$BODY_HEAD" | GH_TRUSTED_HARNESSES="unknown" bash "$TARGET")" \
    "ORIGIN_TRUST=review ORIGIN_HARNESS=unknown ORIGIN_MODEL=unknown"

# 14. The escape hatch skips the gate wholesale (F-5) — and still never
#     reports `trusted`, so a caller grepping for it cannot be fooled.
chk "GH_ISSUE_SKIP_ORIGIN_GATE=1 skips" \
    "$(printf '%s' "${BODY_HEAD}
Generated by Harness(opencode) and LLM(sonnet-4)" \
        | GH_ISSUE_SKIP_ORIGIN_GATE=1 bash "$TARGET")" \
    "ORIGIN_TRUST=skipped ORIGIN_HARNESS=unknown ORIGIN_MODEL=unknown"

# 15. NF-1 end to end: the documented caller idiom against a helper that is
#     not there at all must land on `review`, never `trusted`.
MISSING="$ROOT/lib/origin-trust.sh.does-not-exist"
ORIGIN=$(printf '%s' "${BODY_HEAD}
Generated by Harness(claude) and LLM(opus-5)" | bash "$MISSING" 2>/dev/null) \
    || ORIGIN="ORIGIN_TRUST=review ORIGIN_HARNESS=unknown"
chk "missing helper: caller idiom falls back to review" \
    "$ORIGIN" "ORIGIN_TRUST=review ORIGIN_HARNESS=unknown"

# 16. Same for a helper present but broken (non-zero exit, garbage stdout).
BROKEN=$(mktemp) || exit 1
trap 'rm -f "$BROKEN"; rm -rf "$_globdir"' EXIT
printf '#!/bin/sh\nprintf "ORIGIN_TRUST=trusted\\n"\nexit 1\n' >"$BROKEN"
ORIGIN=$(printf '%s' "$BODY_HEAD" | bash "$BROKEN" 2>/dev/null) \
    || ORIGIN="ORIGIN_TRUST=review ORIGIN_HARNESS=unknown"
chk "broken helper: caller idiom discards its stdout" \
    "$ORIGIN" "ORIGIN_TRUST=review ORIGIN_HARNESS=unknown"

[ "$FAIL" = "0" ] && echo "All checks passed." || echo "SOME CHECKS FAILED."
exit "$FAIL"
